name: Tests unitaires et déploiement Docker

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les tests
        run: pytest tests/

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test  
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Connexion SSH vers l'instance EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          script: |
            cd scoring_credit/
            git pull
            sudo docker ps
            sudo docker stop docker_scoring_credit || true
            sudo docker rm docker_scoring_credit || true
            sudo docker build -t docker_scoring_credit .
            sudo docker run -d -p 8501:8501 -p 8000:8000 --name docker_scoring_credit docker_scoring_credit:latest

